In [62]:
import os
from dotenv import load_dotenv

import pandas as pd
from sqlalchemy import create_engine

In [63]:
def load_database():

    load_dotenv()

    DB_NAME = os.getenv("DB_NAME")
    DB_USER = os.getenv('DB_USER')
    DB_PASSWORD = os.getenv('DB_PASSWORD')
    HOST = os.getenv('HOST')
    PORT = os.getenv('PORT')

    engine_string = "postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}".format(
        user = DB_USER,
        password = DB_PASSWORD,
        host = HOST,
        port = PORT,
        database = DB_NAME,
    )
    
    return create_engine(engine_string)

    
engine = load_database()

In [64]:
# table = db['TABLES'][0]
df = pd.read_sql_table('mobility_google', engine)

In [65]:
df.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AF,Afghanistan,None,None,None,None,None,ChIJbQL_-LZu0TgReNqWvg1GtfM,2020-03-31,-43.0,-29.0,-14.0,-42.0,-38.0,12.0
1,AF,Afghanistan,None,None,None,None,None,ChIJbQL_-LZu0TgReNqWvg1GtfM,2020-04-01,-44.0,-24.0,-9.0,-38.0,-37.0,11.0
2,AF,Afghanistan,None,None,None,None,None,ChIJbQL_-LZu0TgReNqWvg1GtfM,2020-04-02,-44.0,-25.0,-10.0,-35.0,-35.0,13.0
3,AF,Afghanistan,None,None,None,None,None,ChIJbQL_-LZu0TgReNqWvg1GtfM,2020-04-03,-38.0,-13.0,-8.0,-32.0,-12.0,6.0
4,AF,Afghanistan,None,None,None,None,None,ChIJbQL_-LZu0TgReNqWvg1GtfM,2020-04-04,-43.0,-20.0,-11.0,-38.0,-34.0,10.0